### ISSUE TITLE
Error when no type fuzzy matches returned

### ISSUE THREAD

**Issue by dills122** [dills122/MTG-Card-Analyzer#35]
This error is due to the typeMatches array being empty and trying to access the inner array element that doesn't exist. Need to add check for any matches returned before trying to access the matches.

Image used
`E:\GitHub\mtg-card-analyzer\src\test-images\TranquilThicket.jpg`

Needs to 

Error
```
TypeError: this.matches.typeMatches[0] is not iterable
    at SingleProcessor._processOutputFile (E:\GitHub\mtg-card-analyzer\src\processor\processor.js:159:60)
    at SingleProcessor.wrapper [as _processOutputFile] (E:\GitHub\mtg-card-analyzer\node_modules\lodash\lodash.js:4935:19)
    at SingleProcessor.generateOutput (E:\GitHub\mtg-card-analyzer\src\processor\processor.js:76:10)
    at SingleProcessor.wrapper [as generateOutput] (E:\GitHub\mtg-card-analyzer\node_modules\lodash\lodash.js:4935:19)
    at processor.execute (E:\GitHub\mtg-card-analyzer\index.js:28:39)
    at _processCard (E:\GitHub\mtg-card-analyzer\src\processor\processor.js:46:16)
    at CreateDirectory.then.then.then.then (E:\GitHub\mtg-card-analyzer\src\processor\processor.js:67:16)
```

**Comment by dills122** [comment]
Closing — verified current `MatchType()` in [match-type.mjs](https://github.com/dills122/MTG-Card-Analyzer/blob/master/src/fuzzy-matching/match-type.mjs): when no fuzzy match clears the threshold it returns `[]` instead of throwing/erroring. Behavior described in this issue no longer reproduces.
